version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: subtrack-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: subtrack
      POSTGRES_USER: subtrack
      POSTGRES_PASSWORD: subtrack
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
